name: Docker Laravel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker and Start Containers
        working-directory: ./server
        run: |
          cp .env.example .env
          docker compose up -d --build

      - name: Wait for MySQL to be Ready
        working-directory: ./server
        run: |
          echo "Waiting for DB to be ready..."
          until docker compose exec -T backend mysqladmin ping -hdb --silent; do
            sleep 2
          done

      - name: Install Dependencies (Composer)
        working-directory: ./server
        run: |
          docker compose exec -T backend composer install --no-interaction --no-progress --optimize-autoloader

      - name: Generate App Key and JWT Secret
        working-directory: ./server
        run: |
          docker compose exec -T backend php artisan key:generate
          docker compose exec -T backend php artisan jwt:secret --force

      - name: Run Migrations
        working-directory: ./server
        run: docker compose exec -T backend php artisan migrate --force

      - name: Run Tests
        working-directory: ./server
        run: docker compose exec -T backend php artisan test
