name: Laravel Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Navigate to server and start Docker containers
        working-directory: ./server
        run: |
          cp .env.example .env
          docker compose up -d --build

      - name: Install dependencies inside container
        working-directory: ./server
        run: |
          docker compose exec -T app composer install --no-interaction --no-progress --optimize-autoloader

      - name: Generate app key & JWT secret
        working-directory: ./server
        run: |
          docker compose exec -T app php artisan key:generate
          docker compose exec -T app php artisan jwt:secret --force

      - name: Run DB migrations
        working-directory: ./server
        run: |
          docker compose exec -T app php artisan migrate --force

      - name: Run tests
        working-directory: ./server
        run: |
          docker compose exec -T app php artisan test
