name: Docker Laravel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy .env and Start Docker Containers
        run: |
          cp server/.env.example server/.env
          docker compose up -d --build

      - name: Wait for MySQL to be Ready
        run: |
          echo "Waiting for MySQL container to be ready..."
          until docker compose exec -T db mysqladmin ping -hlocalhost --silent; do
            sleep 2
          done

      - name: Install Composer Dependencies
        run: |
          docker compose exec -T backend composer install --no-interaction --no-progress --optimize-autoloader

      - name: Generate App Key and JWT Secret
        run: |
          docker compose exec -T backend php artisan key:generate
          docker compose exec -T backend php artisan jwt:secret --force

      - name: Run Database Migrations
        run: docker compose exec -T backend php artisan migrate --force

      - name: Run Laravel Tests
        run: docker compose exec -T backend php artisan test
